server:  
  port: 8766
  tomcat:
    accesslog:
      enabled: true
    
     
spring:  
  cloud:  
    config:  
      enabled: true  
      server:  
#        svn:  
#          uri: svn://192.168.25.100/src  
#          username: kung 
#          password: 123456
#          searchPaths: test_config
#          basedir: /temp/config-pro
        git:  
          uri: https://github.com/lzredking/config-repo.git
          username: redkingyang@foxmail.com
          password: yourpassword
          basedir: /temp/config-repo 
          search-paths: config-server
        default-label: master
        prefix: /config
#          
#  profiles:  
#    active: subversion
    # local storage,search path ‘src/main/resource’
  #  active: native
  application:
    name: "config-server"

    
  thymeleaf:
    prefix: "classpath:/static/"  
    
logging:  
  level:  
    org.springframework.boot.env.PropertySourcesLoader: TRACE  
    org.springframework.cloud.config.server: DEBUG  
    

